In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy,edge_process
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')
Dataset='/Fire/'
Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Intensity\Preprocessing\image_preprocessing\edge_process.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=5
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=22:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
p_video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in p_video:
    start=5
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=22:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * len(video)
y =[1]*len(p_video)
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    164.38365 212.3516 251.4654 312.6156 205.60248...      0
1    281.75586 174.03131 173.71799 255.81352 238.56...      0
2    1425.3519 1373.9668 1437.9149 1633.4954 1862.8...      0
3    8588.636 15606.876 9383.27 9314.141 4888.855 7...      0
4    8995.766 8062.0996 9380.41 5809.6294 5657.079 ...      0
..                                                 ...    ...
263  15548.207 10682.514 40535.824 114278.97 44923....      1
264  23801.676 78610.445 23310.027 23148.64 13286.7...      1
265  13305.759 18995.36 3942.528 3642.4514 3436.859...      1
266  9760.23 10156.101 14908.927 33021.06 23952.771...      1
267  17943.27 14343.605 18915.57 13119.688 16002.31...      1

[268 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Combine/20/CDI_Based/Intensity/CSV'+Dataset+'Optical_Mag.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,Class
0,164.38365,212.3516,251.4654,312.6156,205.60248,1391.4722,159.75049,122.36173,113.72629,277.6809,121.005295,158.83286,243.68231,288.03723,410.0701,441.60355,379.8768,1398.7834,0
1,281.75586,174.03131,173.71799,255.81352,238.5696,1427.168,184.71503,135.5878,100.2147,204.60022,281.4342,325.38364,434.73547,435.28314,518.0449,914.143,449.55862,2467.9111,0
2,1425.3519,1373.9668,1437.9149,1633.4954,1862.8259,1739.5151,1861.4957,1799.5569,2314.3167,1630.7493,1676.1675,1445.5511,1349.4707,1676.284,1532.1061,1503.2603,1570.2098,1742.7628,0
3,8588.636,15606.876,9383.27,9314.141,4888.855,7578.763,8542.561,6993.378,4309.377,308.34467,86.86575,57.78449,5.6253295,2.9655285,2.965872,2.965872,1.3545805,3908.442,0
4,8995.766,8062.0996,9380.41,5809.6294,5657.079,7049.233,8797.438,15244.262,25340.262,23412.88,21283.285,26272.488,28703.637,52994.87,59666.29,20668.38,10549.264,3290.1765,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,15548.207,10682.514,40535.824,114278.97,44923.434,231827.56,24199.584,45027.01,98061.03,12173.319,9159.67,6429.3706,9306.083,11710.026,11704.487,9859.623,15381.029,8233.648,1
264,23801.676,78610.445,23310.027,23148.64,13286.738,19847.719,15851.057,41467.383,15868.182,10131.911,17415.95,24142.004,12490.38,13592.53,8032.7056,8559.471,13853.692,12117.484,1
265,13305.759,18995.36,3942.528,3642.4514,3436.8596,2727.4072,5521.2056,3281.4182,5210.2983,4085.912,7026.8076,6401.373,8524.062,3571.1235,4132.2764,2351.6658,2268.4426,4443.415,1
266,9760.23,10156.101,14908.927,33021.06,23952.771,60413.11,73798.99,40640.223,34467.555,21913.082,23598.982,35767.91,23413.604,121140.95,14662.49,11355.047,11260.518,7024.2285,1
267,17943.27,14343.605,18915.57,13119.688,16002.315,30350.26,7829.767,3971.8237,4405.2065,8011.633,4183.2812,4114.571,4982.4404,4794.359,4611.1035,3215.7544,3561.279,5640.7627,1