In [21]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')
datasets=['Explosion','Road_Accident','Fighting','Robbery','Burglary']
for data_name in datasets:
    
    Home_os='D:/new/'+data_name+'/'
    negative_os=Home_os+'negative/'
    positive_os=Home_os+'positive/'
    
    video=os.listdir(negative_os)
    #My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    Intensity_list=[]
    for i in video:
        start=0
        video_name=negative_os+i
        cap = cv.VideoCapture(video_name)
        My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
        in_list=[]
        while 1:
            if start<=27:
                cdi,frame=My_CDI.CDI(start,methods='HARRIS')
                Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
                in_list.append(Intensity)
                cv.imshow('frame',frame)
                cv.imshow('cdi',cdi)
                k = cv.waitKey(1) 
                start+=1
                if k ==27:     
                    break 
            else:
                break
        Intensity_list.append(in_list)
        cap.release()
    cv.destroyAllWindows() 

    video=os.listdir(positive_os)
    #My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    P_Intensity_list=[]
    for i in video:
        start=0
        video_name=positive_os+i
        cap = cv.VideoCapture(video_name)
        My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
        in_list=[]
        while 1:
            if start<=27:
                cdi,frame=My_CDI.CDI(start,methods='HARRIS')
                Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
                in_list.append(Intensity)
                cv.imshow('frame',frame)
                cv.imshow('cdi',cdi)
                k = cv.waitKey(1) 
                start+=1
                if k ==27:     
                    break 
            else:
                break
        P_Intensity_list.append(in_list)
        cap.release()
    cv.destroyAllWindows() 
    

    Combine_Intensity=Intensity_list+P_Intensity_list
    # min_max_scaler =MinMaxScaler()
    # for i in range(len(Combine_Intensity)):
    #     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
    new_list=[]
    for i in Combine_Intensity:
            str1 = ' '.join([str(x) for x in i])
            new_list.append(str1)

    print(len(new_list))
    
    x = [0] * len(Intensity_list)
    y =[1]*len(P_Intensity_list)
    z=x+y
    combine_dict={'intensity':new_list,'label':z}
    df=pd.DataFrame(combine_dict)

    display(df)
    y=df['label'].values

    data_df = df['intensity'].str.split(' ', expand=True)

    data_df['Class'] =y
    data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Combine/CDI/Intensity/CSV/'+data_name+'/Harris.csv')
    display(data_df)

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Combine\CDI\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Combine\CDI\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb
268

                                             intensity  label
0    8387460.0 8182950.0 7413870.0 6560895.0 620160...      0
1    7926930.0 6828900.0 6209505.0 6040695.0 590503...      0
2    11175885.0 10896915.0 10621770.0 10857135.0 11...      0
3    6038400.0 6346950.0 6706755.0 7220580.0 597643...      0
4    10903290.0 9469170.0 7526580.0 6321195.0 84269...      0
..                                                 ...    ...
263  8514195.0 8468550.0 8509860.0 8980080.0 866082...      1
264  1523625.0 2946015.0 1535100.0 1768935.0 766453...      1
265  368220.0 184365.0 192525.0 8599620.0 8963760.0...      1
266  11967915.0 12115560.0 12149730.0 12324660.0 12...      1
267  3298935.0 2310300.0 3691125.0 5324400.0 719661...      1

[268 rows x 2 columns]

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,8387460.0,8182950.0,7413870.0,6560895.0,6201600.0,5718120.0,5478675.0,5391210.0,5164770.0,4852650.0,...,6988275.0,7047435.0,7063245.0,8062335.0,6954105.0,5475870.0,4732545.0,5461845.0,6606030.0,0
1,7926930.0,6828900.0,6209505.0,6040695.0,5905035.0,5853015.0,5612040.0,5258355.0,5859135.0,6254640.0,...,7633170.0,7233840.0,6284475.0,6943650.0,7811415.0,6442320.0,5949915.0,5768100.0,5553900.0,0
2,11175885.0,10896915.0,10621770.0,10857135.0,11167470.0,10576380.0,10460355.0,10468770.0,10571280.0,11231730.0,...,11057565.0,11205720.0,11454090.0,11670585.0,11459955.0,10980045.0,10952250.0,11203680.0,11254425.0,0
3,6038400.0,6346950.0,6706755.0,7220580.0,5976435.0,5829300.0,6578490.0,5869590.0,5935125.0,7064010.0,...,50235.0,50235.0,50235.0,50235.0,777240.0,386580.0,64515.0,66045.0,68085.0,0
4,10903290.0,9469170.0,7526580.0,6321195.0,8426985.0,9631350.0,8346915.0,10157415.0,10444290.0,10208925.0,...,11846280.0,10688070.0,10856370.0,12573285.0,7583445.0,7606395.0,11005800.0,7631385.0,5657430.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,8514195.0,8468550.0,8509860.0,8980080.0,8660820.0,8246700.0,8040405.0,7793310.0,8313000.0,8417040.0,...,6560895.0,6814620.0,6188085.0,6415800.0,6481590.0,6519330.0,7117050.0,6403815.0,6524430.0,1
264,1523625.0,2946015.0,1535100.0,1768935.0,7664535.0,7745370.0,7105320.0,6554520.0,5051805.0,4399770.0,...,7040805.0,6890865.0,6630765.0,6636375.0,6441810.0,6178140.0,6334455.0,4881465.0,4220760.0,1
265,368220.0,184365.0,192525.0,8599620.0,8963760.0,8838045.0,8674080.0,8719980.0,8917605.0,8901795.0,...,7707120.0,6250560.0,3846420.0,4408440.0,8053155.0,7959060.0,8973450.0,9092280.0,9194535.0,1
266,11967915.0,12115560.0,12149730.0,12324660.0,12343020.0,11976075.0,11969190.0,12313695.0,12389430.0,12129585.0,...,12142080.0,12026055.0,12202770.0,12202770.0,12289980.0,12476130.0,12408300.0,12368775.0,12093885.0,1
267,3298935.0,2310300.0,3691125.0,5324400.0,7196610.0,7099710.0,7061460.0,7958550.0,7821360.0,7951155.0,...,6711345.0,6179925.0,5989950.0,7658670.0,6559875.0,6424980.0,6175335.0,5881320.0,6589200.0,1

311

                                             intensity  label
0    914175.0 857310.0 839970.0 636735.0 461295.0 3...      0
1    2281485.0 3077340.0 3157665.0 2425305.0 284299...      0
2    1051110.0 371535.0 131580.0 207570.0 1946160.0...      0
3    3315000.0 5601585.0 8766390.0 9109875.0 614550...      0
4    8706210.0 5968275.0 4696080.0 3967800.0 420112...      0
..                                                 ...    ...
306  10135230.0 9640785.0 8659545.0 7080075.0 62617...      1
307  2574225.0 1707225.0 3557505.0 3427200.0 433525...      1
308  3857130.0 1122255.0 1023315.0 4704750.0 560694...      1
309  5521005.0 2017560.0 1799280.0 5478420.0 777393...      1
310  6304365.0 6515250.0 4130235.0 4080765.0 603228...      1

[311 rows x 2 columns]

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,914175.0,857310.0,839970.0,636735.0,461295.0,337875.0,586755.0,437070.0,306765.0,1228845.0,...,421260.0,212160.0,294015.0,5376930.0,2757315.0,648975.0,521985.0,547485.0,640815.0,0
1,2281485.0,3077340.0,3157665.0,2425305.0,2842995.0,2621910.0,1108740.0,1240065.0,1398420.0,1041420.0,...,911880.0,1046520.0,950640.0,1292595.0,917745.0,696915.0,967980.0,733890.0,657645.0,0
2,1051110.0,371535.0,131580.0,207570.0,1946160.0,645660.0,218535.0,247350.0,88485.0,64260.0,...,2040.0,56355.0,53550.0,166005.0,699465.0,359805.0,165240.0,168045.0,126990.0,0
3,3315000.0,5601585.0,8766390.0,9109875.0,6145500.0,1649850.0,2584680.0,11753715.0,11899065.0,8361705.0,...,6043500.0,11697105.0,11930685.0,11641515.0,430695.0,297075.0,7131075.0,7768065.0,3476160.0,0
4,8706210.0,5968275.0,4696080.0,3967800.0,4201125.0,4495905.0,5234895.0,6241125.0,6912030.0,4866930.0,...,2844270.0,2998290.0,2852940.0,3562095.0,6625410.0,4248555.0,3603150.0,3516195.0,2575245.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,10135230.0,9640785.0,8659545.0,7080075.0,6261780.0,6676155.0,7715790.0,9514815.0,10412415.0,8769450.0,...,6114645.0,8428005.0,8238030.0,8711565.0,6369645.0,5107395.0,6203130.0,6844200.0,7114755.0,1
307,2574225.0,1707225.0,3557505.0,3427200.0,4335255.0,2397000.0,1837275.0,5024010.0,7738230.0,5053590.0,...,4380135.0,6410700.0,6900300.0,7734150.0,4714440.0,4058580.0,4163895.0,4180470.0,4888095.0,1
308,3857130.0,1122255.0,1023315.0,4704750.0,5606940.0,6086595.0,4235805.0,990930.0,1231905.0,3755895.0,...,504645.0,622965.0,5592915.0,7553355.0,5564865.0,1820955.0,502605.0,736695.0,4043280.0,1
309,5521005.0,2017560.0,1799280.0,5478420.0,7773930.0,5069910.0,4900590.0,1243890.0,1179120.0,4101165.0,...,1851810.0,1792140.0,5502390.0,11675685.0,6648870.0,5106885.0,5448585.0,7681875.0,6209250.0,1
310,6304365.0,6515250.0,4130235.0,4080765.0,6032280.0,4865910.0,5819100.0,6707010.0,5947365.0,3925725.0,...,3610800.0,5242035.0,6447675.0,7418970.0,5419260.0,4709340.0,5684715.0,4187100.0,4129470.0,1

289

                                             intensity  label
0    3560310.0 2979675.0 5092350.0 1493535.0 242760...      0
1    10315770.0 9446985.0 10219635.0 9846060.0 6166...      0
2    1366035.0 807075.0 945030.0 605625.0 679575.0 ...      0
3    5971845.0 2814945.0 1366035.0 1340280.0 327190...      0
4    3997890.0 4716735.0 9139710.0 8317845.0 292561...      0
..                                                 ...    ...
284  5809665.0 5735460.0 6180945.0 5761980.0 556665...      1
285  7751745.0 3348660.0 3396090.0 4389570.0 308856...      1
286  9568620.0 8643480.0 8764860.0 9913380.0 964716...      1
287  7787445.0 7544430.0 9319485.0 8575650.0 725169...      1
288  6203640.0 5223930.0 5689305.0 8316570.0 809268...      1

[289 rows x 2 columns]

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,3560310.0,2979675.0,5092350.0,1493535.0,242760.0,160905.0,194055.0,93585.0,62220.0,39270.0,...,6490260.0,6330885.0,5120910.0,6434415.0,8055195.0,5803545.0,5139525.0,6588180.0,3989985.0,0
1,10315770.0,9446985.0,10219635.0,9846060.0,6166410.0,6322470.0,8988495.0,8540715.0,8793165.0,9222585.0,...,6478530.0,7416930.0,8539695.0,9567600.0,9467895.0,8049585.0,7297590.0,7993740.0,7083135.0,0
2,1366035.0,807075.0,945030.0,605625.0,679575.0,4238865.0,2533170.0,954975.0,980220.0,1093695.0,...,2630070.0,2207790.0,2754255.0,4236825.0,3547305.0,2547195.0,1694220.0,1544280.0,2598195.0,0
3,5971845.0,2814945.0,1366035.0,1340280.0,3271905.0,7486290.0,7312125.0,5672475.0,5880810.0,5611530.0,...,4490550.0,4304655.0,3375180.0,4447200.0,6104445.0,2953665.0,2922810.0,4206735.0,5382540.0,0
4,3997890.0,4716735.0,9139710.0,8317845.0,2925615.0,1809990.0,3545010.0,4147575.0,1381590.0,1699065.0,...,2686425.0,6114900.0,4365600.0,4771305.0,6871485.0,6156975.0,3329790.0,2811630.0,7301670.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,5809665.0,5735460.0,6180945.0,5761980.0,5566650.0,5610765.0,5732655.0,5773200.0,6092460.0,6269940.0,...,5991225.0,4728975.0,2317950.0,2595900.0,6435690.0,6059310.0,5943795.0,5662785.0,5501115.0,1
285,7751745.0,3348660.0,3396090.0,4389570.0,3088560.0,3684750.0,4282980.0,4749885.0,4432155.0,2714730.0,...,2934030.0,2618595.0,4204695.0,10589130.0,8537400.0,4733310.0,2763945.0,2466615.0,3280830.0,1
286,9568620.0,8643480.0,8764860.0,9913380.0,9647160.0,9694335.0,9756555.0,7370010.0,7397805.0,10040880.0,...,8813055.0,9359265.0,10478205.0,10797720.0,9260070.0,8344110.0,7509240.0,7899900.0,9655830.0,1
287,7787445.0,7544430.0,9319485.0,8575650.0,7251690.0,6643770.0,8138580.0,8344365.0,6734295.0,7245570.0,...,7053555.0,6812835.0,7751235.0,12183390.0,10847445.0,9368700.0,7055595.0,5682930.0,6999495.0,1
288,6203640.0,5223930.0,5689305.0,8316570.0,8092680.0,6885510.0,7534485.0,7571205.0,7945035.0,8045505.0,...,10695720.0,9868245.0,9735900.0,10643445.0,7937640.0,7592370.0,7509750.0,5761980.0,6167685.0,1

283

                                             intensity  label
0    5472300.0 5730615.0 7299885.0 7552335.0 942021...      0
1    4982700.0 4559910.0 8177850.0 7633170.0 645226...      0
2    7494960.0 6969405.0 4769265.0 4082805.0 497275...      0
3    9712185.0 6027690.0 1361190.0 1169940.0 657645...      0
4    11323020.0 8645265.0 6008310.0 6338280.0 86450...      0
..                                                 ...    ...
278  10920885.0 11192970.0 10853055.0 10801035.0 97...      1
279  7978440.0 7950135.0 9266445.0 9258030.0 889491...      1
280  10720455.0 9517875.0 8885475.0 8718705.0 79162...      1
281  7219815.0 4844490.0 5118615.0 6117960.0 344964...      1
282  7877460.0 5895600.0 6431865.0 8189835.0 696175...      1

[283 rows x 2 columns]

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,5472300.0,5730615.0,7299885.0,7552335.0,9420210.0,9180255.0,8064630.0,6988275.0,7652040.0,9164955.0,...,6502500.0,3879315.0,1516995.0,2514810.0,7236390.0,5095410.0,3735240.0,2661945.0,3657720.0,0
1,4982700.0,4559910.0,8177850.0,7633170.0,6452265.0,3894870.0,2813925.0,2075445.0,1372155.0,1685040.0,...,3687300.0,4026195.0,618885.0,1345125.0,0.0,0.0,1746495.0,256785.0,23460.0,0
2,7494960.0,6969405.0,4769265.0,4082805.0,4972755.0,4925580.0,5745660.0,6407895.0,5363925.0,5772945.0,...,3878295.0,3519000.0,4578525.0,7232820.0,4831485.0,3548580.0,4835310.0,6701145.0,5563335.0,0
3,9712185.0,6027690.0,1361190.0,1169940.0,6576450.0,9554850.0,10160220.0,7839465.0,5779575.0,4971735.0,...,6256425.0,6712875.0,5795895.0,7564830.0,4767225.0,3182145.0,3623040.0,1180395.0,223635.0,0
4,11323020.0,8645265.0,6008310.0,6338280.0,8645010.0,9527055.0,9768795.0,8980590.0,8350995.0,7670655.0,...,5949150.0,5881065.0,6419370.0,8882415.0,8025360.0,5921610.0,5701545.0,5919825.0,5819100.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,10920885.0,11192970.0,10853055.0,10801035.0,9749415.0,9668580.0,11088930.0,9689490.0,9757065.0,10444290.0,...,10948680.0,10610295.0,10972395.0,11618055.0,11540280.0,10959390.0,10863000.0,10406550.0,9503340.0,1
279,7978440.0,7950135.0,9266445.0,9258030.0,8894910.0,8720745.0,8979315.0,9301125.0,9390120.0,9377370.0,...,7267245.0,7481700.0,9460755.0,9755280.0,9372525.0,9238650.0,8352015.0,8187540.0,8634300.0,1
280,10720455.0,9517875.0,8885475.0,8718705.0,7916220.0,8382105.0,10653900.0,11147325.0,10142370.0,9040005.0,...,7189725.0,9238395.0,8782200.0,9382725.0,10047765.0,6712620.0,5531460.0,4821540.0,3540930.0,1
281,7219815.0,4844490.0,5118615.0,6117960.0,3449640.0,3519765.0,5046705.0,4176390.0,4454595.0,4993920.0,...,5713785.0,4936545.0,4598925.0,6727155.0,5919570.0,5481480.0,7694880.0,6640455.0,4984485.0,1
282,7877460.0,5895600.0,6431865.0,8189835.0,6961755.0,6734805.0,6475980.0,5165535.0,5516160.0,8014905.0,...,4533135.0,6013410.0,7385055.0,7885110.0,8186520.0,7213950.0,6827370.0,6966090.0,7361085.0,1

268

                                             intensity  label
0    8702895.0 7822125.0 7977165.0 8336715.0 754366...      0
1    9272055.0 9612990.0 8949480.0 8290560.0 866847...      0
2    12299925.0 10031955.0 9532410.0 11581335.0 114...      0
3    7505670.0 4026705.0 2764710.0 3217845.0 653565...      0
4    7991955.0 5726280.0 2689995.0 3049545.0 686995...      0
..                                                 ...    ...
263  6565230.0 6916365.0 6284985.0 5812725.0 568497...      1
264  7465890.0 7143570.0 6905655.0 7248375.0 713898...      1
265  5621220.0 3794910.0 1264290.0 689265.0 668865....      1
266  7504140.0 7099200.0 7309065.0 7688505.0 722262...      1
267  824415.0 4368915.0 6339555.0 6154935.0 8656485...      1

[268 rows x 2 columns]

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,8702895.0,7822125.0,7977165.0,8336715.0,7543665.0,7204770.0,7019640.0,6174570.0,6573900.0,6584355.0,...,4850865.0,5131110.0,4438530.0,5480205.0,8476455.0,5380755.0,4319955.0,4103205.0,4357695.0,0
1,9272055.0,9612990.0,8949480.0,8290560.0,8668470.0,8069475.0,7088490.0,7715025.0,8439990.0,8129910.0,...,8204625.0,9601770.0,8300250.0,8825805.0,8180145.0,7635975.0,8716155.0,6454815.0,6523665.0,0
2,12299925.0,10031955.0,9532410.0,11581335.0,11438280.0,7724715.0,7944780.0,11011155.0,9040005.0,9620130.0,...,4928640.0,6581295.0,10021245.0,10227285.0,12263715.0,9085395.0,4619580.0,5410335.0,10280070.0,0
3,7505670.0,4026705.0,2764710.0,3217845.0,6535650.0,8089110.0,7637250.0,7196355.0,6361230.0,5555685.0,...,4403340.0,4432410.0,4456125.0,5669160.0,6325530.0,4359990.0,4788900.0,5636265.0,5230050.0,0
4,7991955.0,5726280.0,2689995.0,3049545.0,6869955.0,7474050.0,7209105.0,6322980.0,5264475.0,4516560.0,...,3757170.0,3598050.0,4082040.0,6345420.0,7001535.0,5038290.0,4502535.0,3825000.0,3552150.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,6565230.0,6916365.0,6284985.0,5812725.0,5684970.0,5741070.0,5510295.0,5181600.0,4914615.0,5170635.0,...,5878770.0,3716880.0,4212345.0,8315295.0,7774950.0,7125720.0,6860010.0,6972210.0,7250160.0,1
264,7465890.0,7143570.0,6905655.0,7248375.0,7138980.0,6879900.0,7294275.0,7672950.0,7649490.0,7741035.0,...,6951555.0,7240215.0,7861650.0,8165865.0,7866495.0,7596960.0,7433250.0,7552080.0,7419735.0,1
265,5621220.0,3794910.0,1264290.0,689265.0,668865.0,1292850.0,3490185.0,1994610.0,1303305.0,1100580.0,...,2015775.0,2344215.0,2831775.0,5518200.0,5036760.0,3676080.0,3153585.0,2848095.0,3015885.0,1
266,7504140.0,7099200.0,7309065.0,7688505.0,7222620.0,7465125.0,7806570.0,7721400.0,7890465.0,7736445.0,...,6863070.0,7412595.0,7836150.0,8248230.0,7659945.0,7083900.0,7725990.0,7624755.0,7041570.0,1
267,824415.0,4368915.0,6339555.0,6154935.0,8656485.0,3976725.0,3959895.0,8103645.0,5663550.0,4404870.0,...,3747990.0,8477475.0,2612475.0,2664495.0,8178615.0,6842415.0,7553610.0,9846060.0,7858590.0,1