In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fight/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fight\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fight\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

248

In [5]:
x = [0] * 159
y =[1]*89
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    43860 19125 51510 26520 6120 255 255 255 0 0 0...      0
1    143310 133620 168555 158100 84405 122910 20859...      0
2    28560 39780 14790 31620 38760 13260 12240 1683...      0
3    69615 36975 28560 27285 37485 71145 38505 3085...      0
4    24225 111690 11985 4845 100470 32385 14025 135...      0
..                                                 ...    ...
243  290700 302175 272085 241485 251175 290700 2766...      1
244  39015 35700 73185 44880 43605 82365 113730 920...      1
245  327675 297075 361590 332520 349860 379440 3297...      1
246  200175 223890 232305 237405 239700 290445 2725...      1
247  147390 180540 195840 238425 230520 226695 2246...      1

[248 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fight/CDI_Based/Intensity/CSV/Canny_No_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,43860,19125,51510,26520,6120,255,255,255,0,0,...,56100,53040,29580,63240,74970,25755,26775,33405,24480,0
1,143310,133620,168555,158100,84405,122910,208590,151980,167280,170085,...,138975,141015,125970,172890,102000,63750,81345,111690,88740,0
2,28560,39780,14790,31620,38760,13260,12240,16830,15555,19890,...,118320,86955,98175,88995,190485,91035,64770,41565,37995,0
3,69615,36975,28560,27285,37485,71145,38505,30855,19380,17850,...,34170,35700,765,5610,10965,19635,69615,39270,40545,0
4,24225,111690,11985,4845,100470,32385,14025,135150,15045,3570,...,90780,13515,7650,92310,5865,3825,52020,8415,19380,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,290700,302175,272085,241485,251175,290700,276675,324360,284580,318240,...,450075,410805,332265,360825,364905,356745,337620,283305,271575,1
244,39015,35700,73185,44880,43605,82365,113730,92055,109905,138465,...,224145,269790,283050,274125,257295,290955,308040,246585,226440,1
245,327675,297075,361590,332520,349860,379440,329715,329715,326910,438855,...,425340,423555,478635,506430,558195,510765,482970,489345,504135,1
246,200175,223890,232305,237405,239700,290445,272595,254235,267495,260610,...,157845,188955,181815,203745,204765,176460,163455,174930,161925,1
247,147390,180540,195840,238425,230520,226695,224655,257805,211140,184365,...,230265,200175,219555,236895,225420,212670,215730,220575,245565,1