In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fight/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fight\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fight\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

248

In [5]:
x = [0] * 159
y =[1]*89
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    974.5286 1021.10583 733.9467 323.47324 147.781...      0
1    1940.3961 2075.6128 2021.9432 1901.088 2507.09...      0
2    904.7345 612.0881 575.09186 1788.8434 649.3316...      0
3    2819.3704 1158.5739 1018.35004 724.5085 2299.9...      0
4    6376.813 5647.0767 12177.108 4188.4126 10041.6...      0
..                                                 ...    ...
243  9708.565 7871.8394 10119.028 6880.452 6471.348...      1
244  1395.8772 1998.3304 2806.112 2290.1772 2741.35...      1
245  3840.249 3020.5234 3361.5842 3332.348 3564.228...      1
246  5253.4014 8737.798 8185.131 8652.45 17818.28 1...      1
247  3722.0437 3840.0752 2898.0586 4379.001 6503.13...      1

[248 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fight/CDI_Based/Intensity/CSV/Optical_Mag.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Class
0,974.5286,1021.10583,733.9467,323.47324,147.78178,133.92369,225.4314,15.949368,1.1298232,7.9495583,...,2793.6543,1038.327,946.93353,1234.839,2852.7375,1529.4309,1366.3126,1377.7064,2545.589,0
1,1940.3961,2075.6128,2021.9432,1901.088,2507.0962,4273.011,4342.3267,3514.2527,3018.1958,5977.498,...,5187.99,1303.0308,1182.2451,1702.8861,2679.834,1407.5487,1403.4031,617.9451,702.4869,0
2,904.7345,612.0881,575.09186,1788.8434,649.33167,915.9879,598.5762,552.89465,2353.0957,1093.0303,...,7964.101,7612.7266,4893.39,7428.3447,4419.074,2546.4014,5731.0366,2850.3994,1404.1722,0
3,2819.3704,1158.5739,1018.35004,724.5085,2299.9348,1202.8955,1565.5427,766.6247,665.2682,1261.2208,...,405.22372,1990.4294,331.2483,389.2246,2528.394,1643.2102,2728.2622,6097.5493,2733.3687,0
4,6376.813,5647.0767,12177.108,4188.4126,10041.603,12163.906,8177.252,8884.491,15412.066,24045.186,...,3842.0918,5149.006,3796.7026,3126.1628,5179.0283,2774.4326,3059.9856,1433.7682,1410.2627,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,9708.565,7871.8394,10119.028,6880.452,6471.348,9999.008,11112.914,12561.155,5558.6123,6547.308,...,16607.209,18579.707,11556.165,9605.503,11375.718,12031.228,11584.715,7313.247,5548.289,1
244,1395.8772,1998.3304,2806.112,2290.1772,2741.3591,3810.7424,3968.4138,5432.4136,8111.8003,5960.1963,...,19700.637,28140.475,24622.299,13923.391,8184.779,6642.657,11660.227,9534.116,6597.907,1
245,3840.249,3020.5234,3361.5842,3332.348,3564.2285,3664.0903,3626.2048,4843.4834,8073.562,4395.9854,...,12588.378,13162.414,14864.813,22104.895,19695.658,10943.388,14772.601,20990.943,17187.055,1
246,5253.4014,8737.798,8185.131,8652.45,17818.28,14053.991,8726.272,11019.775,19208.521,16754.117,...,10244.133,8143.429,9877.28,45263.902,16064.783,13138.27,3687.9036,3554.136,6088.719,1
247,3722.0437,3840.0752,2898.0586,4379.001,6503.135,6190.704,7644.4033,5152.532,7955.3555,9665.598,...,7897.0015,8000.118,6761.879,7407.4316,5078.5537,5536.7344,4107.0283,5013.8643,6470.5063,1