In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Road/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Road\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Road\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

299

In [8]:
x = [0] * 198
y =[1]*101
z=x+y

In [9]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    6120 1785 1020 10965 1530 510 4080 3315 1530 7...      0
1    42075 59415 47940 46665 66810 49215 35445 3391...      0
2    142035 140760 193290 183600 217515 211905 2004...      0
3    58395 51000 186150 187425 72675 27030 25245 14...      0
4    69360 85425 62985 52275 44370 30345 22440 2958...      0
..                                                 ...    ...
294  53805 39525 52275 40800 85170 193035 224910 25...      1
295  52020 51000 159630 125205 134640 94605 84660 3...      1
296  15300 2805 6630 142800 13515 15300 9945 10200 ...      1
297  72420 25245 21420 56610 50490 17595 13770 2091...      1
298  150960 183345 260865 334815 431970 444975 4462...      1

[299 rows x 2 columns]

In [10]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Road/CDI_Based/Intensity/CSV/Canny_No_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,6120,1785,1020,10965,1530,510,4080,3315,1530,7905,...,1785,510,1020,10965,6630,1785,1785,2550,6120,0
1,42075,59415,47940,46665,66810,49215,35445,33915,36465,33405,...,39270,36720,28305,46665,38760,23205,32130,33405,29070,0
2,142035,140760,193290,183600,217515,211905,200430,199665,161925,164985,...,128520,91545,78795,96390,178500,124950,76755,104295,206040,0
3,58395,51000,186150,187425,72675,27030,25245,144075,157845,24735,...,15555,2805,1275,162945,162690,124950,14790,11475,7905,0
4,69360,85425,62985,52275,44370,30345,22440,29580,46410,41055,...,43860,36720,36975,44625,65280,57375,54570,34680,33405,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,53805,39525,52275,40800,85170,193035,224910,255000,241230,214200,...,114750,118065,121890,176205,238935,144075,122910,166515,143820,1
295,52020,51000,159630,125205,134640,94605,84660,314925,129285,138720,...,179010,53295,49980,202470,27540,14790,39015,24480,30090,1
296,15300,2805,6630,142800,13515,15300,9945,10200,1275,0,...,29835,4845,4080,53295,2805,1785,29325,11730,98175,1
297,72420,25245,21420,56610,50490,17595,13770,20910,63240,100470,...,127245,88740,61965,83895,96390,113730,137190,66300,73440,1
298,150960,183345,260865,334815,431970,444975,446250,454920,495210,513060,...,341445,315180,300390,379950,299115,258315,264945,230775,257040,1