In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Theft/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * 145
y =[1]*123
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    110160 106845 110415 108375 182835 149175 1073...      0
1    159630 184365 178755 190230 198645 147645 1471...      0
2    327930 202215 208080 259335 216495 157590 1932...      0
3    68850 39015 35190 25245 65280 85425 81090 5967...      0
4    128265 60180 28560 22695 79050 93840 70890 601...      0
..                                                 ...    ...
263  38250 46410 38760 22440 36975 47430 51510 3009...      1
264  144585 134640 138975 172380 129285 166770 2284...      1
265  30345 25500 11220 24225 30855 49980 42585 5100...      1
266  284070 322320 289425 324615 354960 383010 3845...      1
267  2295 27540 77520 63750 228480 32385 38505 3845...      1

[268 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Theft/CDI_Based/Intensity/CSV/Canny_With_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,110160,106845,110415,108375,182835,149175,107355,82110,107100,48450,...,48195,58395,52785,82110,100470,68085,63750,76500,64260,0
1,159630,184365,178755,190230,198645,147645,147135,151215,183600,148410,...,123675,167025,159630,188445,169575,120615,128775,109650,128775,0
2,327930,202215,208080,259335,216495,157590,193290,264435,154530,135150,...,62985,84915,104040,113730,280500,110160,51510,53295,107610,0
3,68850,39015,35190,25245,65280,85425,81090,59670,70890,42075,...,51765,71910,57630,70890,66810,51510,48195,53040,56355,0
4,128265,60180,28560,22695,79050,93840,70890,60180,34680,33150,...,20400,31620,24225,47430,60435,30600,22695,31875,20145,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,38250,46410,38760,22440,36975,47430,51510,30090,36975,49215,...,23970,12240,26775,390405,361335,361335,322830,326910,336855,1
264,144585,134640,138975,172380,129285,166770,228480,280500,272850,226695,...,156570,201960,269025,228225,245055,210375,211905,230775,203490,1
265,30345,25500,11220,24225,30855,49980,42585,51000,57375,39525,...,71400,68085,71145,101490,61965,62985,93840,66045,69870,1
266,284070,322320,289425,324615,354960,383010,384540,344505,379185,359040,...,309825,349095,200940,175695,331755,327930,316965,334050,337875,1
267,2295,27540,77520,63750,228480,32385,38505,384540,50745,47175,...,23715,395250,17340,21165,388365,291720,131580,166260,236640,1