In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy,edge_process
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Theft/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\edge_process.ipynb

In [2]:
video=os.listdir(negative_os)

Euler_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)

P_Euler_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Euler=Euler_list+P_Euler_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Euler)):
#     Combine_Euler[i] = ((min_max_scaler.fit_transform(np.array(Combine_Euler[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Euler:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * 145
y =[1]*123
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    54 86 86 81 74 75 82 81 84 92 72 81 68 77 63 5...      0
1    14 17 30 44 27 22 46 33 24 41 29 18 46 45 27 3...      0
2    7 53 53 15 28 64 72 38 68 75 4 38 14 66 54 6 3...      0
3    64 37 24 20 45 40 55 68 63 57 45 41 60 61 49 4...      0
4    86 60 21 25 89 83 78 73 64 52 75 83 64 71 62 4...      0
..                                                 ...    ...
263  37 30 51 53 48 42 34 24 22 24 39 38 31 19 26 1...      1
264  6 20 23 8 11 11 7 3 7 7 2 10 10 4 8 16 11 8 11...      1
265  50 33 11 3 2 6 22 10 8 4 14 60 55 29 16 8 9 7 ...      1
266  7 6 10 13 10 8 7 12 6 12 7 14 14 10 10 9 17 12...      1
267  3 42 39 42 22 40 33 8 44 38 13 4 45 52 22 47 4...      1

[268 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Theft/CDI_based/Intensity/CSV/Euler_Num.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,54,86,86,81,74,75,82,81,84,92,...,55,64,47,75,24,66,36,46,42,0
1,14,17,30,44,27,22,46,33,24,41,...,15,14,23,18,24,37,27,46,35,0
2,7,53,53,15,28,64,72,38,68,75,...,41,71,71,61,4,73,39,66,59,0
3,64,37,24,20,45,40,55,68,63,57,...,40,47,41,65,58,42,57,67,49,0
4,86,60,21,25,89,83,78,73,64,52,...,43,43,57,67,72,60,44,40,42,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,37,30,51,53,48,42,34,24,22,24,...,59,33,44,2,6,13,17,20,10,1
264,6,20,23,8,11,11,7,3,7,7,...,12,5,2,3,3,6,6,6,5,1
265,50,33,11,3,2,6,22,10,8,4,...,4,5,8,53,31,15,17,15,14,1
266,7,6,10,13,10,8,7,12,6,12,...,10,13,12,15,23,13,10,9,15,1
267,3,42,39,42,22,40,33,8,44,38,...,45,30,44,41,21,17,16,17,23,1