In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Theft/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='LAPLACIAN')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='LAPLACIAN')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * 145
y =[1]*123
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    37208 27523 29267 28191 25634 23761 20077 1676...      0
1    40946 40271 34884 38205 47269 31681 27444 3177...      0
2    64645 43410 42101 54628 49504 32717 34553 4264...      0
3    27571 13720 14127 13369 24089 33179 27421 2468...      0
4    21140 12649 5324 6083 16993 20555 19698 16037 ...      0
..                                                 ...    ...
263  12964 14179 10701 9426 9538 9467 10112 10139 1...      1
264  42345 36800 35803 46027 39757 40072 56642 6019...      1
265  9640 6830 3064 3488 3884 6262 9244 8167 6132 5...      1
266  82425 86972 83406 86377 83738 82376 93669 8734...      1
267  755 10391 22251 21172 72005 10732 11165 99329 ...      1

[268 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Theft/CDI_Based/Intensity/CSV/Laplacian_With_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,37208,27523,29267,28191,25634,23761,20077,16766,18566,17725,...,15095,15266,13690,18737,36712,20046,18186,18757,20919,0
1,40946,40271,34884,38205,47269,31681,27444,31777,34207,30239,...,32130,41666,32158,39627,38028,28537,33103,20589,24352,0
2,64645,43410,42101,54628,49504,32717,34553,42646,30434,29159,...,13557,17819,26003,29021,58100,23590,10961,13159,24743,0
3,27571,13720,14127,13369,24089,33179,27421,24685,23695,19929,...,17001,19606,17652,22545,27734,16455,18121,24482,19792,0
4,21140,12649,5324,6083,16993,20555,19698,16037,12156,10699,...,9169,8933,10656,19450,21212,11611,10744,9760,8479,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,12964,14179,10701,9426,9538,9467,10112,10139,11011,11542,...,9969,5409,7741,72369,70870,69761,61641,54419,65865,1
264,42345,36800,35803,46027,39757,40072,56642,60192,54229,54013,...,43535,48993,57992,63186,61783,48485,46103,49933,47783,1
265,9640,6830,3064,3488,3884,6262,9244,8167,6132,5751,...,15227,14710,13419,19201,17271,14303,14032,13109,14458,1
266,82425,86972,83406,86377,83738,82376,93669,87347,90687,78393,...,70564,80157,46835,50443,91376,84752,71226,75146,79834,1
267,755,10391,22251,21172,72005,10732,11165,99329,14465,11017,...,8127,118372,5154,5298,116130,92697,42605,57597,72694,1