In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Theft/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Theft\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
print(len(Intensity_list))

intensity_dict={'intensity':Intensity_list}
df=pd.DataFrame(intensity_dict)
#df['label']=0
display(df)
print(type(df['intensity']))
# k=df['intensity'].values
# g=[len(k[i]) for i in range(800)]
# print(g)

145

                                             intensity
0    [41823.715, 41563.625, 37476.82, 41042.082, 42...
1    [43518.508, 49504.777, 44105.477, 43600.54, 43...
2    [35669.863, 34998.965, 35991.562, 37525.26, 38...
3    [39280.543, 35480.996, 32072.943, 32681.535, 3...
4    [41922.047, 39251.04, 39793.89, 39247.73, 3977...
..                                                 ...
140  [40724.562, 38588.94, 44584.312, 43410.63, 462...
141  [42145.91, 39455.094, 37140.76, 41788.8, 40080...
142  [26170.1, 27268.326, 31995.45, 34014.47, 38415...
143  [40209.29, 37072.707, 36800.71, 37639.16, 3913...
144  [42440.53, 42574.87, 44699.93, 43451.246, 4705...

[145 rows x 1 columns]

<class 'pandas.core.series.Series'>

In [4]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [5]:
print(len(P_Intensity_list))
P_intensity_dict={'intensity':P_Intensity_list}
df=pd.DataFrame(P_intensity_dict)
#df['label']=0
display(df)
print(type(df['intensity']))
# k=df['intensity'].values
# g=[len(k[i]) for i in range(800)]
# print(g)

123

                                             intensity
0    [42494.434, 39528.445, 41073.613, 48340.76, 45...
1    [32304.662, 34091.016, 33961.832, 38335.547, 3...
2    [39201.523, 36030.812, 33306.316, 32682.83, 33...
3    [34298.785, 32552.438, 37932.754, 39606.66, 33...
4    [47731.086, 38759.535, 33163.21, 28910.768, 45...
..                                                 ...
118  [38847.418, 40820.625, 39115.355, 39687.34, 40...
119  [37781.05, 32212.83, 34605.086, 37535.81, 3545...
120  [46718.227, 45110.95, 37878.848, 45237.152, 37...
121  [38620.914, 39014.285, 36580.543, 36463.023, 3...
122  [37819.11, 31366.01, 20380.592, 36651.76, 3365...

[123 rows x 1 columns]

<class 'pandas.core.series.Series'>

In [6]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [7]:
x = [0] * 145
y =[1]*123
z=x+y

In [8]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    41823.715 41563.625 37476.82 41042.082 42095.7...      0
1    43518.508 49504.777 44105.477 43600.54 43151.1...      0
2    35669.863 34998.965 35991.562 37525.26 38528.7...      0
3    39280.543 35480.996 32072.943 32681.535 33530....      0
4    41922.047 39251.04 39793.89 39247.73 39775.805...      0
..                                                 ...    ...
263  38847.418 40820.625 39115.355 39687.34 40779.3...      1
264  37781.05 32212.83 34605.086 37535.81 35452.586...      1
265  46718.227 45110.95 37878.848 45237.152 37851.3...      1
266  38620.914 39014.285 36580.543 36463.023 37831....      1
267  37819.11 31366.01 20380.592 36651.76 33653.55 ...      1

[268 rows x 2 columns]

In [9]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Theft/CDI_Based/Intensity/CSV/Optical_Ang.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Class
0,41823.715,41563.625,37476.82,41042.082,42095.73,40019.664,47015.406,43000.53,39471.367,36874.945,...,40521.58,38558.277,41658.59,39041.824,43815.758,41836.59,42522.973,42072.74,43587.98,0
1,43518.508,49504.777,44105.477,43600.54,43151.164,36914.094,43724.055,47598.996,51543.24,40687.82,...,44826.84,40914.42,41197.152,40435.797,52056.137,38308.348,38849.523,42279.547,33997.14,0
2,35669.863,34998.965,35991.562,37525.26,38528.754,37674.734,35113.53,35564.855,37459.32,34255.918,...,38394.57,40916.51,37921.105,37410.08,41592.258,34784.336,39358.715,41374.137,38443.86,0
3,39280.543,35480.996,32072.943,32681.535,33530.332,41302.0,38464.402,39647.945,38139.156,39574.586,...,38144.34,41048.74,43753.855,41195.203,42834.836,36491.535,40469.453,42898.87,42189.152,0
4,41922.047,39251.04,39793.89,39247.73,39775.805,39056.723,38552.44,38444.996,41459.754,40050.562,...,45682.133,43115.465,40289.08,39425.207,39668.312,37328.07,42138.82,41106.855,41546.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,38847.418,40820.625,39115.355,39687.34,40779.348,41866.37,44131.344,42171.883,39407.81,37923.723,...,43880.766,43717.32,39734.613,34208.656,33675.195,30883.793,33314.555,31364.857,26822.361,1
264,37781.05,32212.83,34605.086,37535.81,35452.586,33895.555,35625.562,34750.945,30775.19,34306.78,...,35668.16,35952.32,36421.523,35523.926,42666.617,35020.66,33219.414,32677.086,35527.36,1
265,46718.227,45110.95,37878.848,45237.152,37851.348,49219.707,51065.527,43746.414,36786.56,39571.438,...,49171.125,38693.71,36114.957,44893.277,49464.934,46945.258,48009.453,44597.863,42969.152,1
266,38620.914,39014.285,36580.543,36463.023,37831.92,36308.89,38915.363,38581.46,35917.27,33530.773,...,43871.875,41435.27,33991.723,38995.297,35563.332,33568.707,31472.967,32266.3,31063.422,1
267,37819.11,31366.01,20380.592,36651.76,33653.55,40548.914,41636.145,44349.367,45530.77,31322.256,...,47837.01,33798.11,32546.797,43417.3,34734.21,32465.047,35994.973,44804.008,32453.14,1