In [3]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy,edge_process
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Road/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

In [4]:
video=os.listdir(negative_os)

Euler_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [5]:
video=os.listdir(positive_os)

P_Euler_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [6]:

Combine_Euler=Euler_list+P_Euler_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Euler)):
#     Combine_Euler[i] = ((min_max_scaler.fit_transform(np.array(Combine_Euler[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Euler:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

299

In [7]:
x = [0] * 198
y =[1]*101
z=x+y

In [8]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    7 5 6 6 4 2 3 5 4 12 32 17 11 6 3 4 1 3 20 3 0...      0
1    17 31 37 26 24 29 9 10 16 8 10 5 4 7 6 3 4 4 4...      0
2    41 37 29 31 34 30 36 41 34 22 6 28 52 56 63 63...      0
3    91 82 50 34 67 44 34 48 38 22 37 44 22 30 34 2...      0
4    26 23 60 62 50 54 20 25 63 56 56 59 19 16 12 1...      0
..                                                 ...    ...
294  12 8 4 8 6 5 5 10 35 16 45 12 14 32 1 1 1 1 41...      1
295  33 25 33 13 12 27 28 6 7 3 3 1 6 5 3 21 21 18 ...      1
296  49 13 9 21 12 8 7 8 12 5 46 23 12 14 3 1 1 3 1...      1
297  77 9 11 71 47 18 6 7 19 62 56 20 12 12 47 51 1...      1
298  23 44 28 17 7 4 7 9 9 8 3 18 18 9 6 7 4 9 16 6...      1

[299 rows x 2 columns]

In [9]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Road/CDI_based/Intensity/CSV/Euler_Num.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,7,5,6,6,4,2,3,5,4,12,...,3,0,1,61,29,10,7,8,7,0
1,17,31,37,26,24,29,9,10,16,8,...,5,5,6,11,5,4,7,3,4,0
2,41,37,29,31,34,30,36,41,34,22,...,39,44,49,50,11,62,36,48,41,0
3,91,82,50,34,67,44,34,48,38,22,...,24,5,2,37,41,15,16,12,12,0
4,26,23,60,62,50,54,20,25,63,56,...,20,26,28,42,49,62,53,22,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,12,8,4,8,6,5,5,10,35,16,...,32,23,26,28,12,42,29,22,17,1
295,33,25,33,13,12,27,28,6,7,3,...,17,35,40,9,52,36,20,32,37,1
296,49,13,9,21,12,8,7,8,12,5,...,30,5,10,17,11,15,46,29,24,1
297,77,9,11,71,47,18,6,7,19,62,...,95,37,8,22,30,24,39,12,8,1
298,23,44,28,17,7,4,7,9,9,8,...,6,9,9,5,3,3,8,23,10,1