In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Road/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Road\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Road\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
print(len(Intensity_list))

intensity_dict={'intensity':Intensity_list}
df=pd.DataFrame(intensity_dict)
#df['label']=0
display(df)
print(type(df['intensity']))
# k=df['intensity'].values
# g=[len(k[i]) for i in range(800)]
# print(g)

198

                                             intensity
0    [43336.727, 33569.94, 30666.002, 29588.512, 29...
1    [32834.84, 38182.83, 35685.1, 34116.01, 35598....
2    [28718.951, 31597.617, 30235.166, 26487.748, 3...
3    [39172.766, 31761.213, 31054.273, 29064.91, 34...
4    [31926.115, 37403.49, 40343.105, 40755.977, 34...
..                                                 ...
193  [41487.203, 44455.64, 39025.797, 38126.996, 40...
194  [37822.215, 37486.797, 36743.914, 38117.254, 3...
195  [49451.66, 44248.695, 43941.223, 45631.445, 43...
196  [41780.273, 42460.46, 35023.113, 34618.15, 362...
197  [35074.047, 34377.25, 35512.426, 38255.863, 36...

[198 rows x 1 columns]

<class 'pandas.core.series.Series'>

In [4]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [5]:
print(len(P_Intensity_list))
P_intensity_dict={'intensity':P_Intensity_list}
df=pd.DataFrame(P_intensity_dict)
#df['label']=0
display(df)
print(type(df['intensity']))
# k=df['intensity'].values
# g=[len(k[i]) for i in range(800)]
# print(g)

101

                                             intensity
0    [41667.305, 42507.36, 38662.64, 42424.824, 394...
1    [33794.336, 29758.844, 31613.438, 38685.895, 3...
2    [37942.266, 42576.305, 39279.87, 36677.336, 44...
3    [41108.535, 38979.152, 36375.613, 39118.695, 4...
4    [37041.37, 37418.535, 41095.566, 38596.645, 40...
..                                                 ...
96   [29208.229, 28799.502, 27538.496, 27054.766, 3...
97   [40108.55, 30650.125, 29228.871, 36315.176, 49...
98   [42762.977, 43446.78, 37244.98, 33451.168, 450...
99   [37530.78, 31000.885, 38593.082, 40292.72, 388...
100  [48738.875, 47533.895, 44295.457, 40746.344, 3...

[101 rows x 1 columns]

<class 'pandas.core.series.Series'>

In [15]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

299

In [9]:
x = [0] * 198
y =[1]*101
z=x+y

In [16]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    43336.727 33569.94 30666.002 29588.512 29435.8...      0
1    32834.84 38182.83 35685.1 34116.01 35598.727 3...      0
2    28718.951 31597.617 30235.166 26487.748 31180....      0
3    39172.766 31761.213 31054.273 29064.91 34773.6...      0
4    31926.115 37403.49 40343.105 40755.977 34271.9...      0
..                                                 ...    ...
294  29208.229 28799.502 27538.496 27054.766 30339....      1
295  40108.55 30650.125 29228.871 36315.176 49213.7...      1
296  42762.977 43446.78 37244.98 33451.168 45088.03...      1
297  37530.78 31000.885 38593.082 40292.72 38850.83...      1
298  48738.875 47533.895 44295.457 40746.344 39648....      1

[299 rows x 2 columns]

In [17]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Road/CDI_Based/Intensity/CSV/Optical_Ang.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Class
0,43336.727,33569.94,30666.002,29588.512,29435.867,27627.98,42563.79,35676.754,38029.51,39578.52,...,33282.523,23411.719,22318.283,37298.008,47840.426,40303.223,38673.145,33158.82,40910.8,0
1,32834.84,38182.83,35685.1,34116.01,35598.727,33035.52,30562.307,32555.066,29933.047,29475.639,...,33522.78,30990.22,36963.51,41474.0,53753.727,27280.7,34868.44,32564.215,33242.67,0
2,28718.951,31597.617,30235.166,26487.748,31180.646,31568.105,32524.191,32335.613,34583.15,38609.336,...,40954.957,40209.203,36087.785,39053.18,45004.125,40702.95,36783.18,38979.203,34722.004,0
3,39172.766,31761.213,31054.273,29064.91,34773.652,34544.35,29591.22,33338.26,38961.96,41886.742,...,40806.062,35097.125,38056.746,29876.498,35388.53,37137.79,33483.062,39754.902,45856.996,0
4,31926.115,37403.49,40343.105,40755.977,34271.973,36751.01,33900.406,36866.945,43540.008,36312.445,...,40656.645,39760.29,40287.19,36524.5,40956.523,37129.26,40142.766,36176.13,36875.992,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,29208.229,28799.502,27538.496,27054.766,30339.975,22860.355,27519.705,27853.559,34006.8,31646.062,...,41400.754,33919.348,32509.674,32306.633,33792.188,35503.605,38035.297,30755.297,35570.88,1
295,40108.55,30650.125,29228.871,36315.176,49213.72,54031.08,42052.625,40114.36,61605.848,38570.293,...,31892.143,39289.18,39497.61,32936.426,35813.94,38732.633,41102.75,41035.34,36283.367,1
296,42762.977,43446.78,37244.98,33451.168,45088.03,36306.426,43977.992,37888.85,35707.293,43645.402,...,42209.59,40799.43,39974.082,42087.754,43662.992,42063.344,42132.05,43180.21,41135.914,1
297,37530.78,31000.885,38593.082,40292.72,38850.836,38396.273,31551.53,35984.977,40101.047,46177.21,...,38658.12,38828.477,36478.38,34360.734,41945.18,35872.54,39419.52,33713.97,28926.238,1
298,48738.875,47533.895,44295.457,40746.344,39648.695,36806.35,38064.973,40386.85,34255.09,45890.227,...,36952.902,38954.94,41556.273,38757.227,41301.992,38912.41,37840.867,45883.66,39530.547,1