In [8]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy,edge_process
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fight/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

In [9]:
video=os.listdir(negative_os)

Euler_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [10]:
video=os.listdir(positive_os)

P_Euler_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [11]:

Combine_Euler=Euler_list+P_Euler_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Euler)):
#     Combine_Euler[i] = ((min_max_scaler.fit_transform(np.array(Combine_Euler[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Euler:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

247

In [12]:
x = [0] * 159
y =[1]*88
z=x+y

In [13]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    34 18 58 17 2 0 2 2 0 0 0 24 11 2 3 2 2 2 2 44...      0
1    55 55 48 60 44 49 56 53 66 71 34 11 65 61 45 6...      0
2    57 58 58 52 85 22 10 11 46 70 76 14 6 12 65 14...      0
3    80 12 6 6 9 68 15 6 7 17 3 15 4 5 9 79 17 3 10...      0
4    44 52 32 18 22 54 28 8 22 26 13 19 4 5 12 21 1...      0
..                                                 ...    ...
242  7 6 4 12 16 15 4 2 2 1 1 6 7 7 2 4 1 6 8 1 1 5...      1
243  43 41 36 28 36 57 57 44 34 34 51 55 31 35 35 2...      1
244  5 23 15 9 11 12 30 17 16 5 6 13 15 21 28 15 9 ...      1
245  44 35 22 26 36 33 31 36 30 50 37 14 47 45 59 3...      1
246  34 39 33 49 35 30 26 21 20 12 41 36 11 12 8 7 ...      1

[247 rows x 2 columns]

In [14]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fight/CDI_based/Intensity/CSV/Euler_Num.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,34,18,58,17,2,0,2,2,0,0,...,44,65,42,70,62,49,47,62,47,0
1,55,55,48,60,44,49,56,53,66,71,...,55,54,49,35,33,95,70,66,83,0
2,57,58,58,52,85,22,10,11,46,70,...,42,35,14,27,3,69,22,11,8,0
3,80,12,6,6,9,68,15,6,7,17,...,28,87,12,14,7,6,81,12,7,0
4,44,52,32,18,22,54,28,8,22,26,...,14,38,20,14,18,12,27,20,16,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,7,6,4,12,16,15,4,2,2,1,...,1,1,5,3,8,7,7,10,12,1
243,43,41,36,28,36,57,57,44,34,34,...,26,31,35,31,56,35,39,33,34,1
244,5,23,15,9,11,12,30,17,16,5,...,5,10,11,19,8,9,9,9,17,1
245,44,35,22,26,36,33,31,36,30,50,...,23,27,57,57,15,17,43,21,26,1
246,34,39,33,49,35,30,26,21,20,12,...,16,21,16,40,32,16,10,14,14,1