In [8]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fight/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

In [9]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='HARRIS')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [10]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='HARRIS')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [11]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

247

In [12]:
x = [0] * 159
y =[1]*88
z=x+y

In [13]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    3560310.0 2979675.0 5092350.0 1493535.0 242760...      0
1    10315770.0 9446985.0 10219635.0 9846060.0 6166...      0
2    5972865.0 6231690.0 4830975.0 5693130.0 710940...      0
3    7234860.0 2377620.0 1864305.0 1620780.0 213307...      0
4    5065065.0 5948385.0 2515575.0 1640160.0 374977...      0
..                                                 ...    ...
242  7456200.0 7752000.0 7679325.0 7572990.0 741336...      1
243  5189505.0 4740450.0 4935525.0 4624935.0 470067...      1
244  10624320.0 7466910.0 7559475.0 9772875.0 98827...      1
245  9652005.0 7828500.0 7580385.0 8591205.0 960814...      1
246  6874800.0 6863580.0 7669125.0 7346550.0 706171...      1

[247 rows x 2 columns]

In [14]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fight/CDI_Based/Intensity/CSV/Harris_No_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,3560310.0,2979675.0,5092350.0,1493535.0,242760.0,160905.0,194055.0,93585.0,62220.0,39270.0,...,6490260.0,6330885.0,5120910.0,6434415.0,8055195.0,5803545.0,5139525.0,6588180.0,3989985.0,0
1,10315770.0,9446985.0,10219635.0,9846060.0,6166410.0,6322470.0,8988495.0,8540715.0,8793165.0,9222585.0,...,6478530.0,7416930.0,8539695.0,9567600.0,9467895.0,8049585.0,7297590.0,7993740.0,7083135.0,0
2,5972865.0,6231690.0,4830975.0,5693130.0,7109400.0,2249865.0,1608285.0,1729665.0,3264510.0,5458530.0,...,8048055.0,3971625.0,2737170.0,3747735.0,10261200.0,7899900.0,3675825.0,2102730.0,1919640.0,0
3,7234860.0,2377620.0,1864305.0,1620780.0,2133075.0,6064410.0,2260065.0,1510110.0,1325490.0,1758225.0,...,3083460.0,5175990.0,1042185.0,1325745.0,1256640.0,1249755.0,6127905.0,2869005.0,1614660.0,0
4,5065065.0,5948385.0,2515575.0,1640160.0,3749775.0,3906855.0,2305710.0,2943465.0,1567740.0,1695495.0,...,3348150.0,2911590.0,1881390.0,3466215.0,1767150.0,1524390.0,4188120.0,1892610.0,1141125.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,7456200.0,7752000.0,7679325.0,7572990.0,7413360.0,7283565.0,7558710.0,7873890.0,7740015.0,7699725.0,...,8060040.0,8018985.0,7987620.0,8137305.0,7734150.0,7543665.0,7618890.0,7431720.0,7361595.0,1
243,5189505.0,4740450.0,4935525.0,4624935.0,4700670.0,6363015.0,7114245.0,6550950.0,6979350.0,6566250.0,...,6886275.0,8188050.0,8549640.0,8852835.0,8724315.0,7361595.0,7765005.0,7959825.0,7218285.0,1
244,10624320.0,7466910.0,7559475.0,9772875.0,9882780.0,10740345.0,9480645.0,8174280.0,8565195.0,10341525.0,...,10866315.0,10387425.0,9215445.0,9511500.0,9718305.0,9421740.0,10554705.0,10493760.0,9591315.0,1
245,9652005.0,7828500.0,7580385.0,8591205.0,9608145.0,10110495.0,9887880.0,9303930.0,9525015.0,9884055.0,...,5800230.0,6532845.0,8592225.0,9694590.0,10706175.0,9184335.0,7268265.0,5274930.0,5181600.0,1
246,6874800.0,6863580.0,7669125.0,7346550.0,7061715.0,6520350.0,6242145.0,5714805.0,5365710.0,5442975.0,...,6659835.0,6503010.0,6489240.0,7590075.0,6106230.0,5151510.0,5227755.0,5230305.0,5744895.0,1