In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fight/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fight\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fight\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
print(len(Intensity_list))

intensity_dict={'intensity':Intensity_list}
df=pd.DataFrame(intensity_dict)
#df['label']=0
display(df)
print(type(df['intensity']))
# k=df['intensity'].values
# g=[len(k[i]) for i in range(800)]
# print(g)

159

                                             intensity
0    [45150.242, 48629.625, 44090.41, 37707.14, 283...
1    [37454.508, 40205.25, 38159.773, 36232.28, 358...
2    [37208.95, 42731.9, 42513.16, 42038.723, 36727...
3    [37740.695, 31125.031, 28135.69, 27234.002, 36...
4    [34280.484, 40930.11, 41556.125, 33093.383, 36...
..                                                 ...
154  [33538.04, 30284.148, 31961.217, 36762.88, 332...
155  [37144.46, 37068.586, 39322.254, 40121.18, 431...
156  [45253.94, 47526.773, 45467.688, 37622.33, 396...
157  [40673.523, 37807.984, 38992.81, 38325.39, 391...
158  [33653.867, 33284.2, 30088.486, 42919.88, 3727...

[159 rows x 1 columns]

<class 'pandas.core.series.Series'>

In [4]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [5]:
print(len(P_Intensity_list))
P_intensity_dict={'intensity':P_Intensity_list}
df=pd.DataFrame(P_intensity_dict)
#df['label']=0
display(df)
print(type(df['intensity']))
# k=df['intensity'].values
# g=[len(k[i]) for i in range(800)]
# print(g)

89

                                            intensity
0   [42081.227, 39317.12, 37285.82, 37375.824, 420...
1   [30298.12, 41833.07, 41060.41, 30227.803, 3241...
2   [30674.451, 33144.26, 35993.79, 36455.355, 378...
3   [45175.25, 52714.5, 48229.64, 40141.72, 36756....
4   [33110.145, 27229.8, 33356.707, 45532.613, 338...
..                                                ...
84  [32354.523, 30230.592, 30931.117, 26552.04, 31...
85  [38541.316, 39178.785, 52363.516, 45574.996, 4...
86  [36058.715, 37014.11, 37038.832, 40846.1, 4089...
87  [36426.01, 31157.795, 29297.82, 33259.043, 324...
88  [35821.25, 34923.508, 36753.992, 36463.574, 35...

[89 rows x 1 columns]

<class 'pandas.core.series.Series'>

In [6]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

248

In [9]:
x = [0] * 159
y =[1]*89
z=x+y

In [10]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    45150.242 48629.625 44090.41 37707.14 28336.33...      0
1    37454.508 40205.25 38159.773 36232.28 35860.93...      0
2    37208.95 42731.9 42513.16 42038.723 36727.484 ...      0
3    37740.695 31125.031 28135.69 27234.002 36128.0...      0
4    34280.484 40930.11 41556.125 33093.383 36629.7...      0
..                                                 ...    ...
243  32354.523 30230.592 30931.117 26552.04 31966.8...      1
244  38541.316 39178.785 52363.516 45574.996 42108....      1
245  36058.715 37014.11 37038.832 40846.1 40895.758...      1
246  36426.01 31157.795 29297.82 33259.043 32430.27...      1
247  35821.25 34923.508 36753.992 36463.574 35518.2...      1

[248 rows x 2 columns]

In [11]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fight/CDI_Based/Intensity/CSV/Optical_Ang.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Class
0,45150.242,48629.625,44090.41,37707.14,28336.334,25038.332,40529.688,33754.86,35617.883,21151.139,...,44247.12,52964.57,49727.105,48713.81,56395.332,51491.28,50960.547,45955.336,48286.68,0
1,37454.508,40205.25,38159.773,36232.28,35860.934,39269.41,35058.88,37169.617,37897.113,31618.91,...,40190.402,35026.06,35752.227,33197.387,37520.586,44156.05,44806.664,35205.305,37084.76,0
2,37208.95,42731.9,42513.16,42038.723,36727.484,38190.895,39947.78,39037.527,42288.42,41991.8,...,33230.484,36407.055,40706.96,40104.32,41555.05,45222.957,39997.34,39501.258,35279.77,0
3,37740.695,31125.031,28135.69,27234.002,36128.035,37315.105,34042.543,26357.703,29350.994,39445.17,...,37488.953,42868.363,38618.938,33114.527,48533.76,36138.816,40070.145,41829.547,40802.39,0
4,34280.484,40930.11,41556.125,33093.383,36629.727,43054.035,32163.94,34008.402,44126.39,37388.133,...,32284.543,43436.305,44949.5,33699.848,40849.387,45292.21,42355.66,41709.074,39558.242,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,32354.523,30230.592,30931.117,26552.04,31966.855,31389.924,26789.701,34137.48,31902.625,31251.36,...,39127.258,32049.574,30884.938,27731.28,29902.227,31716.686,36350.867,36950.324,36608.715,1
244,38541.316,39178.785,52363.516,45574.996,42108.27,42757.758,43015.918,45576.98,44105.43,38217.55,...,36455.812,36625.56,36582.188,38318.906,43280.867,42948.418,46625.367,43395.387,43310.34,1
245,36058.715,37014.11,37038.832,40846.1,40895.758,41213.883,38399.492,41437.6,43144.67,37304.13,...,40414.2,39834.668,38691.785,37818.82,41662.09,39249.38,34702.383,37580.63,36565.406,1
246,36426.01,31157.795,29297.82,33259.043,32430.277,32376.656,32886.664,37325.645,33406.734,33865.65,...,34495.906,33295.664,34984.645,38167.508,37873.426,29861.34,37656.527,35208.926,33342.793,1
247,35821.25,34923.508,36753.992,36463.574,35518.293,31308.035,28428.566,26204.521,35585.047,35607.21,...,30518.62,33023.062,33232.254,30087.303,34574.363,30717.209,31312.477,33012.387,34409.543,1